title: Noticias AEE
email: aee@epn.edu.ec
description: >-
  Página web dedicada a dar novedades acerca de la carrera de Ingeniería Eléctrica EPN.
url: "https://AEE-EPN.github.io" 
baseurl: ""
theme: minima
timezone: America/Guayaquil
header_pages:
  - index.md
  - recursos.md
  - auspiciantes.md
exclude:
  - resources
